### ISSUE TITLE
[jak2] [high fps] hosehead gets stuck jumping down in sewer escort (240 fps)

### ISSUE THREAD

**Issue by atre13** [open-goal/jak-project#3207]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Sometimes the three NPCs you escort get stuck on the first elevator of the level and once I got past that they get stuck in the first dark corner every time after the first combat engagement with 2 metal heads.

### How To Reproduce

Consistently getting stuck in the dark corner.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

The three NPCs should keep moving and blow up the debris that is blocking the path forward if I remember correctly.

### Environment Information

Windows 10 Pro
Ryzen 5 5600x
RTX 4070
OpenGOAL version 2.4.0
Tooling version 0.2.2

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

Yes

**Comment by Hat-Kid** [comment]
This bug happens at 240 FPS (rarely also at 165), lowering your frame rate should fix it.

**Comment by Derek-aka-Derek** [comment]
first encounter has 3 enemies the enemy climbing down the wall in the left corner is launched away at high fps causing a soft lock

**Comment by Feemdog** [comment]
Lowering framerates doesn't seem to fix the issue.

**Comment by ManDude** [comment]
Lower to 60 and restart the mission.

**Comment by Feemdog** [comment]
Still isn't working for me. I even tried going frame by frame and it still bugs out the metal head, got to see it get launched out of the map though.

**Comment by atre13** [comment]
Can confirm it worked as intended for me as soon as I switched back to 60fps the second time and I was able to finish the game with no problems since then.

Sorry for the late response and a huge thanks to the opengoal project for making it possible to play this amazing game once again but on an even better version.

**Comment by Feemdog** [comment]
[https://youtu.be/RDc-5ddgS1w](url) dont know how to use this site efficiently hope this works though

**Comment by Feemdog** [comment]
I realized what the problem was. I was setting the frame rate to 60 through the toolbar and not through the in-game settings. All good now.

**Comment by xTVaser** [comment]
Reopening as this is a legitimate high-fps issue which would ideally be fixed long-term.
